# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# Increase Bluetooth transmission power for a stable connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Set the Bluetooth name that will appear on your Mac Mini
CONFIG_ZMK_KEYBOARD_NAME="MacroPad 12"
